# ansible requirements.yml
---
roles:
  - src: Oefenweb.apt
    version: v3.2.1
  - src: singleplatform-eng.users
    version: v1.2.6
  - src: geerlingguy.ntp
    version: 2.7.0
  - src: dev-sec.ssh-hardening
    version: 9.7.0
  - src: Oefenweb.fail2ban
    version: v4.0.10
  - src: lae.proxmox
    version: v1.8.1
  - src: geerlingguy.docker
    version: 7.1.0

collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 8.6.1
  - name: community.docker
    version: 3.10.2
  - name: community.sops
    version: 1.6.7
