# ansible requirements.yml
---
roles:
  - src: Oefenweb.apt
    version: v3.2.3
  - src: singleplatform-eng.users
    version: v1.2.6
  - src: geerlingguy.ntp
    version: 2.7.0
  - src: dev-sec.ssh-hardening
    version: 9.7.0
  - src: Oefenweb.fail2ban
    version: v4.0.11
  - src: lae.proxmox
    version: v1.9.1
  - src: geerlingguy.docker
    version: 7.4.4

collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 10.4.0
  - name: community.docker
    version: 4.3.0
  - name: community.sops
    version: 2.0.1
