version: "3"
services:
  nexus:
    image: "sonatype/nexus3"
    container_name: nexus
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/mnt/docker-volumes/nexus-data:/nexus-data"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.nexus-secure.entrypoints=websecure
      - traefik.http.routers.nexus-secure.rule=Host(`nexus.${DOMAIN}`)
      - traefik.http.routers.nexus-secure.service=nexus
      - traefik.http.services.nexus.loadbalancer.server.port=8081
      # Additional labels for Docker registry
      - traefik.http.routers.registry-secure.entrypoints=websecure
      - traefik.http.routers.registry-secure.rule=Host(`registry.${DOMAIN}`)
      - traefik.http.routers.registry-secure.service=registry
      - traefik.http.services.registry.loadbalancer.server.port=8082
    expose:
      - "8081"
      - "8082"
    networks:
      - traefik

networks:
  traefik:
    external: true
