---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Container"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  container:
    name: Container
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    # workflow used to build ansible execution environment with ansible-builder and push it to ghcr.io
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder

      - name: Build container
        run: |
          ansible-builder build -t ghcr.io/${{ github.repository }}/ansible-runner:latest -v 3

      - name: Push container
        run: |
          echo ${{ steps.app-token.outputs.token }} | podman login ghcr.io -u ${{ github.repository }} --password-stdin
          podman push ghcr.io/${{ github.repository }}/ansible-runner:latest
